### ISSUE TITLE
URL Change

### ISSUE THREAD

**Issue by DavidGhedini** [MaZderMind/replicate-sequences#2]
Hi -
The url is going to 404.
I first noticed today, but it may have been earlier.
` curl "https://replicate-sequences.osm.mazdermind.de/?$(date --utc "+%FT%TZ")"
curl: (6) Could not resolve host: replicate-sequences.osm.mazdermind.de; Name or service not known
`

**Comment by MaZderMind** [comment]
Thanks for reporting. Ill fix the Server as soon as I‘m back on a computer. Might take  week though.Am 31.10.2023 um 20:27 schrieb David Ghedini ***@***.***>:﻿
Hi -
The url is going to 404.
I first noticed today, but it may have been earlier.
curl "https://replicate-sequences.osm.mazdermind.de/?$(date --utc "+%FT%TZ")" curl: (6) Could not resolve host: replicate-sequences.osm.mazdermind.de; Name or service not known

**Comment by JanaRoels** [comment]
Hello,
I was wondering what the status for this issue is? Is it something planning to be solved or should we look for another solution?
Kr

**Comment by MaZderMind** [comment]
I'm so sorry … totally lost that between the other millions of burning fires. dns is fixed now and the tool will be reachable again soon.

**Comment by DavidGhedini** [comment]
Many thanks!
